### ISSUE TITLE
Import the CSV of facilities to OpenSRP locations API

### ISSUE THREAD

**Issue by githengi** [opensrp/opensrp-client-chw-emergency-transport#10]
Import the CSV of facilities to OpenSRP locations API

This will be used to render the facilities on the Geowidget

**Comment by githengi** [comment]
LOE 3-4 days for 1 FTE

**Comment by msschroeder** [comment]
@githengi This is no longer needed based on the discussions last week? Correct?

**Comment by githengi** [comment]
@msschroeder Yes this will not be worked on since the facilities will be loaded as a static geojson file.

I have tagged it as wontfix

**Comment by msschroeder** [comment]
@githengi Thank you. I will close this and remove from to do
